- id: 10.1122/1.5134036
  image: https://procf.github.io/images/journal_covers/ecoevorxiv.jpg
  tags:
    - Particle Simulation




- id: 10.1063/1.4919303
  image: https://procf.github.io/images/journal_covers/ecoevorxiv.jpg
  tags:
    - Particle Simulation