- id: 10.1039/C2SM27104D
  image: https://procf.github.io/images/journal_covers/soft_matter.jpg
  tags:
    - Colloidal Systems
  repo_link: 
  main_author: Safa Jamali
    



- id: 10.1016/j.polymertesting.2013.03.005
  image: https://procf.github.io/images/journal_covers/polym_test.jpg
  tags:
    - Colloidal Systems
  repo_link: 
  main_author: Safa Jamali


- id: 10.1063/1.4919303
  image: https://procf.github.io/images/journal_covers/j_chem_phys.jpg
  tags:
    - Colloidal Systems
  repo_link: 
  main_author: Safa Jamali


- id: 10.1016/j.cpc.2015.05.027
  image: https://procf.github.io/images/journal_covers/comp_phys_comm.jpg
  tags:
    - Colloidal Systems
  repo_link: 
  main_author: Safa Jamali


- id: 10.1039/C5SM01560J
  image: https://procf.github.io/images/journal_covers/soft_matter.jpg
  tags:
    - Colloidal Systems
  repo_link: 
  main_author: Safa Jamali


- id: 10.1016/j.cpc.2015.08.003
  image: https://procf.github.io/images/journal_covers/comp_phys_comm.jpg
  tags:
    - Machine Learning
  repo_link: 
  main_author: Safa Jamali


- id: 10.1122/1.4931655
  image: https://procf.github.io/images/journal_covers/j_rheol.jpg
  tags:
    - Colloidal Systems
  repo_link: 
  main_author: Safa Jamali


- id: 10.1021/acs.macromol.6b01011
  image: https://procf.github.io/images/journal_covers/macromol.jpg
  tags:
    - Colloidal Systems
  repo_link: 
  main_author: Safa Jamali


- id: 10.1103/PhysRevLett.119.158001
  image: https://procf.github.io/images/journal_covers/phys_rev_lett.jpg
  tags:
    - Colloidal Systems
  repo_link: 
  main_author: Safa Jamali


- id: 10.1039/C6SM00750C
  image: https://procf.github.io/images/journal_covers/soft_matter.jpg
  tags:
    - Network Science
  repo_link: 
  main_author: Safa Jamali


- id: 10.1103/PhysRevLett.118.048003
  image: https://procf.github.io/images/journal_covers/phys_rev_lett.jpg
  tags:
    - Colloidal Systems
  repo_link: 
  main_author: Safa Jamali


- id: 10.1103/PhysRevLett.123.138002
  image: https://procf.github.io/images/journal_covers/phys_rev_lett.jpg
  tags:
    - Colloidal Systems
  repo_link: 
  main_author: Safa Jamali


- id: 10.1016/j.mtadv.2019.100026
  image: https://procf.github.io/images/journal_covers/mater_today_adv.jpg
  tags:
    - Machine Learning
  repo_link: 
  main_author: Safa Jamali


- id: 10.1103/PhysRevLett.123.248003
  image: https://procf.github.io/images/journal_covers/phys_rev_lett.jpg
  tags:
    - Colloidal Systems
  repo_link: 
  main_author: Safa Jamali


- id: 10.1122/1.5134036
  image: https://procf.github.io/images/journal_covers/j_rheol.jpg
  tags:
    - Colloidal Systems
  repo_link: 
  main_author: Safa Jamali



- id: 10.1016/j.icheatmasstransfer.2020.104978
  image: https://procf.github.io/images/journal_covers/intl_comm_heat_mass_transfer.jpg
  tags:
    - Machine Learning
  repo_link: 
  main_author: Amin Mahmoudabad


- id: 10.1122/8.0000174
  image: https://procf.github.io/images/journal_covers/j_rheol.jpg
  tags:
    - Colloidal Systems
  repo_link: 
  main_author: Safa Jamali


- id: 10.1098/rsif.2020.0834
  image: https://procf.github.io/images/journal_covers/j_royal_soc_interface.jpg
  tags:
    - Hemorheology
  repo_link: 
  main_author: Elahe Javadi


- id: 10.1016/j.bpj.2021.05.013
  image: https://procf.github.io/images/journal_covers/biophys.jpg
  tags:
    - Hemorheology
  repo_link: 
  main_author: Elahe Javadi


- id: 10.1038/s41598-021-91518-3
  image: https://procf.github.io/images/journal_covers/scientific_rep.jpg
  tags:
    - Machine Learning
  repo_link: 
  main_author: Amin Mahmoudabad


- id: 10.1038/s41467-021-24416-x
  image: https://procf.github.io/images/journal_covers/nature_comm.jpg
  tags:
    - Network Science
  repo_link: 
  main_author: Mohammad Nabizadeh


- id: 10.1039/D1SM00856K
  image: https://procf.github.io/images/journal_covers/soft_matter.jpg
  tags:
    - Hemorheology
  repo_link: 
  main_author: Elahe Javadi


- id: 10.1103/PhysRevLett.127.158002
  image: https://procf.github.io/images/journal_covers/phys_rev_lett.jpg
  tags:
    - Colloidal Systems
  repo_link: 
  main_author: Mohammad Nabizadeh


- id: 10.1039/D1SM01298C
  image: https://procf.github.io/images/journal_covers/soft_matter.jpg
  tags:
    - Machine Learning
  repo_link: 
  main_author: Amin Mahmoudabad


- id: 10.1016/j.jcis.2021.11.195
  image: https://procf.github.io/images/journal_covers/j_coll_interface_sci.jpg
  tags:
    - Machine Learning
  repo_link: 
  main_author: Amin Mahmoudabad


- id: 10.1122/8.0000432
  image: https://procf.github.io/images/journal_covers/j_rheol.jpg
  tags:
    - Network Science
  repo_link: 
  main_author: Safa Jamali


- id: 10.1063/5.0079214
  image: https://procf.github.io/images/journal_covers/j_chem_phys.jpg
  tags:
    - Hemorheology
  repo_link: 
  main_author: Elahe Javadi


- id: 10.1073/pnas.2202234119
  image: https://procf.github.io/images/journal_covers/pnas.jpg
  tags:
    - Machine Learning
  repo_link: 
  main_author: Amin Mahmoudabad


- id: 10.1103/PhysRevLett.129.068001
  image: https://procf.github.io/images/journal_covers/phys_rev_lett.jpg
  tags:
    - Colloidal Systems
  repo_link: 
  main_author: Mohammad Nabizadeh


- id: 10.1007/s00397-022-01357-w
  image: https://procf.github.io/images/journal_covers/rheologica_acta.png
  tags:
    - Machine Learning
  repo_link: https://github.com/procf/RhINNs/tree/main/steady_state_model_selection
  main_author: Milad Saadat


- id: 10.1016/j.bpj.2022.08.031
  image: https://procf.github.io/images/journal_covers/biophys.jpg
  tags:
    - Hemorheology
  repo_link: https://github.com/procf/Covid-paper_input-files
  main_author: Elahe Javadi



- id: 10.52768/2766-7820/1916
  image: https://procf.github.io/images/journal_covers/j_clin_med_case_reports.jpg
  tags:
    - Hemorheology
  repo_link: 
  main_author: Elahe Javadi


- id: 10.1063/5.0106700
  image: https://procf.github.io/images/journal_covers/phys_fluids.jpg
  tags:
    - Colloidal Systems
  repo_link: 
  main_author: Ali Mehdizadeh


- id: https://doi.org/10.26434/chemrxiv-2021-dz2d8
  image: https://procf.github.io/images/journal_covers/chemrxiv.jpg
  tags:
    - Machine Learning
  repo_link: 
  main_author: Ali Mehdizadeh


- id: 10.1021/acs.jctc.2c00248
  image: https://procf.github.io/images/journal_covers/j_chem_theory_comp.jpg
  tags:
    - Machine Learning
  repo_link: 
  main_author: Ali Mehdizadeh


- id: 10.1007/s00397-023-01408-w
  image: https://procf.github.io/images/journal_covers/rheologica_acta.png
  tags:
    - Machine Learning
  repo_link: https://github.com/procf/RhINNs/tree/main/fractional_models
  main_author: Donya Dabiri


- id: 10.1007/s00397-023-01416-w
  image: https://procf.github.io/images/journal_covers/rheologica_acta.png
  tags:
    - Machine Learning
  repo_link: 
  main_author: Safa Jamali


- id: 10.1063/5.0169051
  image: https://procf.github.io/images/journal_covers/phys_fluids.jpg
  tags:
    - Hemorheology
  repo_link: 
  main_author: Elahe Javadi


- id: 10.1073/pnas.2313658121
  image: https://procf.github.io/images/journal_covers/pnas.jpg
  tags:
    - Machine Learning
  repo_link: 
  main_author: Amin Mahmoudabad


- id: 10.1103/PhysRevE.109.014602
  image: https://procf.github.io/images/journal_covers/phys_rev_e.jpg
  tags:
    - Colloidal Systems
  repo_link: 
  main_author: Deepak Mangal


- id: 10.1073/pnas.2316394121
  image: https://procf.github.io/images/journal_covers/pnas.jpg
  tags:
    - Network Science
  repo_link: 
  main_author: Mohammad Nabizadeh


- id: 10.1122/8.0000552
  image: https://procf.github.io/images/journal_covers/j_rheol.jpg
  tags:
    - Hemorheology
  repo_link: 
  main_author: Elahe Javadi


- id: 10.1039/D3DD00036B
  image: https://procf.github.io/images/journal_covers/digital_disc.png
  tags:
    - Machine Learning
  repo_link: https://github.com/procf/RhINNs/tree/main/transient_model_selection
  main_author: Milad Saadat


- id: 10.1063/5.0123096
  image: https://procf.github.io/images/journal_covers/jcp_2023.jpeg
  tags:
    - Colloidal Systems
    - Network Science
  repo_link: 
  main_author: Deepak Mangal

- id: 10.1039/D4SM00209A
image: https://procf.github.io/images/journal_covers/soft_matter.jpg
tags:
  - Colloidal Systems
repo_link: 
main_author: Deepak Mangal

- id: 10.1039/D4SM00316K
image: https://procf.github.io/images/journal_covers/soft_matter.jpg
tags:
  - Colloidal Systems
repo_link: 
main_author: Deepak Mangal